apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "remuda-controller.name" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "remuda-controller.labels" . | nindent 4 }}
