apiVersion: v2
name: remuda-controller
description: Keeps Remuda's cross-cluster hop pointing at current downstream node addresses.
type: application
version: 0.2.0-rc.7
appVersion: "0.2.0-rc.7"
home: https://github.com/rak-phillip/remuda
sources:
  - https://github.com/rak-phillip/remuda
annotations:
  catalog.cattle.io/certified: rancher
  catalog.cattle.io/namespace: cattle-remuda-system
  catalog.cattle.io/release-name: remuda-controller
